language: go

os:
  - linux

before_install:
  - mkdir /tmp/helm
  - wget https://kubernetes-helm.storage.googleapis.com/helm-v2.13.0-linux-amd64.tar.gz -O /tmp/helm/helm-v2.13.0-linux-amd64.tar.gz
  - cd /tmp/helm
  - tar xzvf helm-v2.13.0-linux-amd64.tar.gz
  - rm helm-v2.13.0-linux-amd64.tar.gz
  - mv linux-amd64/helm helm
  - chmod u+x helm
  - ./tmp/helm/helm init --client-only

script:
  - mkdir build
  - ./tmp/helm/helm package ./
  - mv *.tgz build/
  - ./tmp/helm/helm repo index build/ --url http://helm-repo.sphera.tools.s3-website-us-east-1.amazonaws.com/consul-helm

deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY_ID}"
  secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  bucket: "helm-repo.sphera.tools"
  skip_cleanup: true
  region: "us-east-1"
  local_dir: build
  upload-dir: consul-helm
