# ConfigMap with extra configuration specified directly to the chart
# for client agents only.
{{- if (or (and (ne (.Values.client.enabled | toString) "-") .Values.client.enabled) (and (eq (.Values.client.enabled | toString) "-") .Values.global.enabled)) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "consul.fullname" . }}-client-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  extra-from-values.json: |-
{{ tpl .Values.client.extraConfig . | trimAll "\"" | indent 4 }}
  {{- if (and .Values.connectInject.enabled .Values.connectInject.centralConfig.enabled) }}
  central-config.json: |-
    {
      "enable_central_service_config": true
    }
  {{- end }}
  {{- if gt (len .Values.client.aclTokens) 0 }}
  acl-config.json: |-
    {
      "acl": {
          "enabled": true,
          "tokens": {
          {{- $lastIndex := sub (len .Values.client.aclTokens) 1}}
          {{- range $i, $token := .Values.client.aclTokens }}
            "{{ $token.type }}": "{{ $token.value }}"{{ if ne $i $lastIndex -}},{{ end }}
          {{- end }}
          }
      }
    }
  {{- end }}
{{- end }}
