{{- if (or (and (ne (.Values.client.enabled | toString) "-") .Values.client.enabled) (and (eq (.Values.client.enabled | toString) "-") .Values.global.enabled)) }}
{{- if .Values.client.snapshotAgent.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "consul.fullname" . }}-snapshot-agent
  labels:
    helm.sh/chart: {{ include "consul.chart" . }}
    app.kubernetes.io/name: {{ include "consul.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
{{- if not (or .Values.global.enablePodSecurityPolicies .Values.global.bootstrapACLs) }}
rules: []
{{- else }}
rules:
{{- end }}
{{- if .Values.global.enablePodSecurityPolicies }}
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    resourceNames:
    - {{ template "consul.fullname" . }}-snapshot-agent
    verbs:
    - use
{{- end }}
{{- if .Values.global.bootstrapACLs }}
  - apiGroups: [""]
    resources:
      - secrets
    resourceNames:
      - {{ .Release.Name }}-consul-client-snapshot-agent-acl-token
    verbs:
      - get
{{- end }}
{{- else }}
{{- end }}
{{- end }}
