# The service for the Connect sidecar injector
{{- if (or (and (ne (.Values.connectInject.enabled | toString) "-") .Values.connectInject.enabled) (and (eq (.Values.connectInject.enabled | toString) "-") .Values.global.enabled)) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "consul.fullname" . }}-connect-injector-svc
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "consul.chart" . }}
    app.kubernetes.io/name: {{ include "consul.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
spec:
  ports:
  - port: 443
    targetPort: 8080
  selector:
    helm.sh/chart: {{ template "consul.chart" . }}
    app.kubernetes.io/name: {{ template "consul.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: connect-injector
{{- end }}
