{{- if .Values.meshGateway.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "consul.fullname" . }}-mesh-gateway
  labels:
    helm.sh/chart: {{ include "consul.chart" . }}
    app.kubernetes.io/name: {{ include "consul.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    component: mesh-gateway
{{- if or .Values.global.bootstrapACLs .Values.global.enablePodSecurityPolicies }}
rules:
{{- if .Values.global.enablePodSecurityPolicies }}
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    resourceNames:
      - {{ template "consul.fullname" . }}-mesh-gateway
    verbs:
      - use
{{- end }}
{{- if .Values.global.bootstrapACLs }}
  - apiGroups: [""]
    resources:
      - secrets
    resourceNames:
      - {{ .Release.Name }}-consul-mesh-gateway-acl-token
    verbs:
      - get
{{- end }}
{{- else }}
rules: []
{{- end }}
{{- end }}
