{{- if (or (and (ne (.Values.server.enabled | toString) "-") .Values.server.enabled) (and (eq (.Values.server.enabled | toString) "-") .Values.global.enabled)) }}
{{- if (or (and (ne (.Values.client.enabled | toString) "-") .Values.client.enabled) (and (eq (.Values.client.enabled | toString) "-") .Values.global.enabled)) }}
{{- if .Values.global.bootstrapACLs }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "consul.fullname" . }}-server-acl-init
  labels:
    helm.sh/chart: {{ include "consul.chart" . }}
    app.kubernetes.io/name: {{ include "consul.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - list
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - create
      - get
{{- if .Values.connectInject.enabled }}
  - apiGroups: [""]
    resources:
      - serviceaccounts
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - services
    verbs:
      - get
{{- end }}
{{- end }}
{{- end }}
{{- end }}
