{{- if (or (and (ne (.Values.snapshot.enabled | toString) "-") .Values.snapshot.enabled) (and (eq (.Values.snapshot.enabled | toString) "-") .Values.global.enabled)) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "consul.fullname" . }}-snapshot
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- end }}
